//! Semantic-to-Kinetic Compiler for HDIT AutoML
//!
//! This module physically lowers the abstract `AutomlPlan` generated by the
//! HDIT AutoML search loop into a deterministic, executable `Motion` packet
//! (POWL8/POWL64) that can be admitted by the UniverseOS Typestate gates.
//!
//! It also provides the CONSTRUCT8 bridge to durably persist the compiled
//! plan back into the Oxigraph semantic ledger (closing the MAPE-K loop).

use crate::ml::hdit_automl::{AutomlPlan, FusionOp, Tier};
use unibit_globe::GlobeCell;
use unibit_lane::FieldLane;
use unibit_powl::{Intensity, Motion, Powl64, Powl64Node, Powl8, Powl8Node};

/// Compile an AutoML plan into a branchless POWL8/POWL64 execution `Motion`.
///
/// This serves as the "Semantic-to-Kinetic Compiler". It takes the chosen
/// orthogonal feature signals and the optimal fusion operation, and lowers
/// them into a concrete machine topology.
pub fn compile_plan_to_motion(plan: &AutomlPlan) -> Result<Motion, String> {
    if plan.selected.is_empty() {
        return Err("Cannot compile an empty AutomlPlan".into());
    }

    let mut k = Powl8::new();
    let mut g = Powl64::new();

    // Store the node IDs of the evaluated signal primitives
    let mut signal_nodes_k = Vec::new();
    let mut signal_nodes_g = Vec::new();

    // 1. Create the T0/T1 sensory input atoms for each selected signal
    for (i, (_name, tier)) in plan.tiers.iter().enumerate() {
        let (lane, intensity) = match tier {
            Tier::T0 => (FieldLane::Law, Intensity::Run), // T0 branchless rules are Laws
            Tier::T1 => (FieldLane::Conformance, Intensity::Run), // T1 sparse projections
            Tier::T2 => (FieldLane::Capability, Intensity::Run), // T2 multi-word models
            Tier::Warm => (FieldLane::Prereq, Intensity::Feel), // Warm external calls
        };

        let node_k = k
            .push(Powl8Node::Activity(lane, intensity))
            .ok_or("Failed to push")?;

        let node_g = g
            .push(Powl64Node::Place(GlobeCell::new(10, i as u16, 0)))
            .ok_or("Failed to push")?;

        signal_nodes_k.push(node_k);
        signal_nodes_g.push(node_g);
    }

    // 2. Map the Fusion Operation into a deterministic execution graph topology
    let (root_k, root_g) = match plan.fusion {
        FusionOp::Single => {
            // A single signal requires no fusion operator, it directly drives output
            (signal_nodes_k[0], signal_nodes_g[0])
        }
        FusionOp::WeightedVote | FusionOp::BordaCount | FusionOp::Stack => {
            // Ensembles evaluate all signals in Parallel (Concur), then execute
            // the fusion operation as a sequential causal capability.

            // Build the parallel execution block for the signals
            let mut current_par_k = signal_nodes_k[0];
            let mut current_par_g = signal_nodes_g[0];

            for i in 1..signal_nodes_k.len() {
                current_par_k = k
                    .push(Powl8Node::OperatorParallel(
                        current_par_k,
                        signal_nodes_k[i],
                    ))
                    .ok_or("Failed to push")?;
                current_par_g = g
                    .push(Powl64Node::Concur(current_par_g, signal_nodes_g[i]))
                    .ok_or("Failed to push")?;
            }

            // Create the fusion operator atom
            let fusion_k = k
                .push(Powl8Node::Activity(FieldLane::Causality, Intensity::Run))
                .ok_or("Failed to push")?;
            let fusion_g = g
                .push(Powl64Node::Place(GlobeCell::new(11, 0, 0)))
                .ok_or("Failed to push")?;

            // Sequence the parallel evaluation into the fusion operator
            let seq_k = k
                .push(Powl8Node::OperatorSequence(current_par_k, fusion_k))
                .ok_or("Failed to push")?;
            let seq_g = g
                .push(Powl64Node::Geodesic(current_par_g, fusion_g))
                .ok_or("Failed to push")?;

            (seq_k, seq_g)
        }
    };

    k.root = root_k;
    g.root = root_g;

    Motion::new(k, g).map_err(|_| "Failed to assemble final Motion".into())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ml::classic_ai_signals::{mycin_automl_signal, strips_automl_signal};
    use crate::ml::hdit_automl::run_hdit_automl;
    use crate::ml::mycin::{fact, org};
    use crate::ml::strips::{ARM_EMPTY, CLEAR_A, CLEAR_B, HOLDING_A, ON_TABLE_A, ON_TABLE_B};
    use oxigraph::store::Store;
    use unibit_graph::construct8_to_oxigraph;

    #[test]
    fn test_mape_k_loop_automl_to_construct8_to_oxigraph() {
        // 1. MONITOR & ANALYZE (Evaluate Trace Data against Heuristics)
        let anchor = vec![true, false, true, false];

        let patients = vec![
            fact::GRAM_POS | fact::COCCUS | fact::AEROBIC | fact::FEVER | fact::RIGORS,
            fact::GRAM_NEG | fact::ANAEROBIC,
            fact::GRAM_POS | fact::COCCUS | fact::AEROBIC | fact::FEVER | fact::RIGORS,
            fact::GRAM_POS | fact::COCCUS | fact::AEROBIC | fact::BURN,
        ];
        let mycin_sig = mycin_automl_signal("mycin_strep", &patients, org::STREP, &anchor);

        let blocks = vec![
            CLEAR_A | ON_TABLE_A | ARM_EMPTY | CLEAR_B | ON_TABLE_B,
            0,
            CLEAR_A | ON_TABLE_A | ARM_EMPTY | CLEAR_B | ON_TABLE_B,
            0,
        ];
        let strips_sig = strips_automl_signal("strips_pickup", &blocks, HOLDING_A, &anchor);

        let candidates = vec![mycin_sig, strips_sig];

        // 2. PLAN (HDIT AutoML Compiler selects optimal operator family and tiers)
        // Set n_target=2 to force it to use multiple signals via BordaCount/WeightedVote
        let plan = run_hdit_automl(candidates, &anchor, 2);

        // 3. EXECUTE (Semantic-to-Kinetic Compilation)
        // Physically lower the abstract plan into a branchless POWL8/POWL64 Motion
        let motion = compile_plan_to_motion(&plan).expect("Failed to compile plan");

        assert!(
            motion.kinetic.len >= 1,
            "Motion must contain kinetic topology"
        );
        assert!(
            motion.geometric.len >= 1,
            "Motion must contain geometric placement"
        );

        // 4. KNOWLEDGE (CONSTRUCT8 Persistence)
        // Close the MAPE-K loop by writing the verified structural footprint
        // to the durable Oxigraph causal ledger.
        let store = Store::new().expect("Failed to create Oxigraph store");

        // This exercises the end-to-end bridge built in unibit-graph
        construct8_to_oxigraph(&store, &motion).expect("CONSTRUCT8 RDF emission failed");

        let triples_count = store.len().expect("Failed to count Oxigraph triples");
        assert!(
            triples_count > 0,
            "Oxigraph store must contain the compiled AutomlPlan knowledge"
        );
    }
}
